sonar.host.url=https://sonarcloud.io
sonar.organization=the-dna-squad
sonar.projectKey=the-dna-squad_vscode-jupyter-main
sonar.projectName=paul.hickey / vscode-jupyter / main

sonar.sources=.
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.spec.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.sourceEncoding=UTF-8
